name: Trivy Security Scan
on:
  workflow_call:
jobs:
  build:
    name: Check for vulnerabilities
    runs-on: ubuntu-20.04
    steps:
      - name: Security check - Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          scan-ref: "."
          severity: "MEDIUM,CRITICAL,HIGH"
          exit-code: "1"
          trivy-config: |
            rules:
              - id: rule1
                category: general
                title: Generic Rule
                severity: 'MEDIUM,CRITICAL,HIGH'
                keywords:
                  - secret
                regex: (?i)(?P<key>(secret))(=|:).{0,5}'\"['\"]
                secret-group-name: secret
