name: Unit tests

on:
  pull_request:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        description: 'Python version, eg 3.11'
        default: '3.11'
        type: string
    
jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt -r requirements.txt

      - name: Run tests
        run: pytest . -vv
